### ISSUE TITLE
Non-static setting conflicts with the game's default attribute bars

### ISSUE THREAD

**Issue by quantumfate** [DakJaniels/FancyActionBarPlus#5]
These screenshots are from the official FAB addon but I checked  and the same behaviour applies to FAB+.

On the frontbar everything looks fine:
![image2](https://github.com/DakJaniels/Fancy.Action.Bar.ESO/assets/62796852/b54e1b83-da24-4fc5-ba62-28b2eba37434)

Swapping to the backbar shows that the attribute bars still attack to the front bar:
![image](https://github.com/DakJaniels/Fancy.Action.Bar.ESO/assets/62796852/aedf2089-c7c9-45f8-a29d-768c12851dd8)

Any idea whether you can fix it? Also will this addon ever be on minion?

**Comment by DakJaniels** [comment]
It will not be published to esoui. I'll look into what is going on with the bars though.

**Comment by ACastanza** [comment]
Hi quantum, part of the issue here is that ZOS's default action bar position simply does not have enough space to put in a full sized backbar above it like FancyActionBar creates.
In order to fix this we would have to, by default, shift down the front-bar position for everyone what uses FAB+.
But I don't know that we can reasonably do so accounting for all the different possible screen-resolutions and action bar sizes. We kind of just have to rely on ZOS's default anchors here.

As I workaround I would suggest configuring your action bar to use the "Static Bar Positions" setting like here:

![image](https://github.com/user-attachments/assets/0485ac44-c75f-44d5-bf15-a1833028f83e)

The downside of this setting is that it requires you to choose if you want your front bar or back bar to always be on top (my personal settings like you can see in the screenshot is for the back bar to always be on top).

That said, what I might try to do here is to add a setting like the "Active Bar on Top" setting, but for use with the static bar positions.

**Comment by ACastanza** [comment]
Hey @quantumfate,
I went ahead and implemented this in FAB+
Enable the "Barswap with Static Bar Positions" setting here:
![image](https://github.com/user-attachments/assets/289102a0-18a3-4ff6-a9db-4b7e1c89e67c)

But you'll need to use this version of FAB+ until we do a proper release with it:
[FancyActionBar+_2.6.4_RC3.zip](https://github.com/user-attachments/files/16401153/FancyActionBar%2B_2.6.4_RC3.zip)

**Comment by ACastanza** [comment]
I just realized, these aren't the game's default attribute bars. This would appear to be an addon that does a "stacked" attribute bar layout. I would check that addon's settings for an option to reposition the stacked bars.

For reference, the game's default attribute bars look like this:
![image](https://github.com/user-attachments/assets/34bfa7f7-8e34-4ca1-b0db-f5c39db5076b)
and do not conflict with FAB's action bar layout.

As to the other comment, I'm pleased to say that we have finally added FAB+ to ESOUI so you can get it from Minion now!

As this is not a conflict with the basegame, but rather with an addon, I'm going to go ahead and close this Issue
